dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.composer/cache

services:
  - rabbitmq

addons:
  apt:
    packages:
      - rabbitmq-server

language: php

php:
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*

install: travis_retry ./tests/travis/install.sh

before_script:
  - curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add -
  - sudo apt-get install apt-transport-https
  - echo "deb http://dl.bintray.com/rabbitmq-erlang/debian xenial erlang-22.x" >  | sudo tee  /etc/apt/sources.list.d/bintray.erlang.list > /dev/null
  - sudo apt-get update -y
  - sudo apt-get install -y erlang-base \
    erlang-asn1 erlang-crypto erlang-eldap erlang-ftp erlang-inets \
    erlang-mnesia erlang-os-mon erlang-parsetools erlang-public-key \
    erlang-runtime-tools erlang-snmp erlang-ssl \
    erlang-syntax-tools erlang-tftp erlang-tools erlang-xmerl

  - sudo cp $TRAVIS_BUILD_DIR/provision/rabbitmq.config /etc/rabbitmq/
  - sudo service rabbitmq-server restart
  - git clone https://github.com/alanxz/rabbitmq-c.git
  - cd rabbitmq-c
  - git checkout v0.8.0
  - git submodule init && git submodule update
  - autoreconf -i && ./configure --prefix=$HOME/rabbitmq-c && make && make install
  - cd ..
  - git clone https://github.com/pdezwart/php-amqp.git
  - cd php-amqp
  - phpize
  - ./configure --with-librabbitmq-dir=$HOME/rabbitmq-c
  - make
  - sudo make install
  - cd ..
  - echo "extension = amqp.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
