dist: trusty
sudo: required

cache:
  directories:
    - $HOME/.composer/cache

services:
  - rabbitmq

language: php

php:
  - 7.1

matrix:
  fast_finish: true
  include:
    - php: 7.1
      env: SYMFONY_VERSION=2.7.*
    - php: 7.1
      env: SYMFONY_VERSION=2.8.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*

install: travis_retry ./tests/travis/install.sh

before_script:
  - composer update --prefer-dist --no-interaction

script:
  - ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover
