---
name: Continuous Integration

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: ['7.1', '7.3', '7.4']
        symfony: ['^4.0', '^5.0']

    services:
      rabbitmq:
        image: rabbitmq:latest
        ports:
        - 5672/tcp
        options: --health-cmd "rabbitmqctl node_health_check" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2

      - name: Set default PHP version
        run: |
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          pecl install amqp

      - name: Get Composer Cache Directory
        id: composer-cache-dir
        run:  echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Cache Composer
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache-dir.outputs.dir }}
          key: composer-${{ hashFiles('composer.json') }}
          restore-keys: |
            composer-

      - name: Install dependencies
        run: |
          composer require --no-interaction \
            symfony/config:${{ matrix.symfony }} \
            symfony/console:${{ matrix.symfony }} \
            symfony/dependency-injection:${{ matrix.symfony }} \
            symfony/framework-bundle:${{ matrix.symfony }} \
            symfony/http-kernel:${{ matrix.symfony }}
          composer install --no-interaction --prefer-source

      - name: PHPUnit
        run: php vendor/bin/phpunit
